### ISSUE TITLE
Overwrite CSV

### ISSUE THREAD

**Issue by clareprice** [Esri/utilities-solution-data-automation#11]
@MikeMillerGIS 

When the CSVOutputLocation is set to a path that exists and merge report is set to true for all reports, though the feature classes will be updated with the most current data the output CSV will not.

Additionally, when the CSVOutputLocation is set to a different CSV name and report merge set to true, no new csv will be created.

**Comment by MikeMillerGIS** [comment]
Not able to repo using the most recent code.  What solution did you repo this on?

**Comment by clareprice** [comment]
@MikeMillerGIS Facility Reports for Gas Distribution.

**Comment by clareprice** [comment]
Issue fixed with most recent reporting tool code.
