### ISSUE TITLE
BUG-000100918  The Facility Reports for Gas Distribution solution report different results when calculating distances as compared to ArcMap.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/utilities-solution-data-automation#20]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100918</span><br/>
<span><b>Salesforce Submitter:</b> Raynah Kamau</span><br/>
<span><b>Salesforce Submit Date:</b> 11/18/2016 1:54 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100918</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS Online</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 4.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
When lines doubled back on themselves (e.g., if viewing in 3D space, the line would look like a Z), the intersect tool converts these into multiple features. When using a non shape length field, this results in that value be counted more than once.

**Comment by MikeMillerGIS** [comment]
beta version available here - https://geonet.esri.com/docs/DOC-9352

**Comment by clareprice** [comment]
This issue has been resolved with the June 27 release of ArcGIS Solutions.
