### ISSUE TITLE
Location tracking not updated using stage app 

### ISSUE THREAD

**Issue by clareprice** [Esri/utilities-solution-data-automation#8]
@MikeMillerGIS 

When creating web maps using the stage app script with location tracking enabled, the layer does not update from the portal item definition to the new web map. Because of this, though there will be a location tracking layer in the map, no location is tracked in this layer when using Collector for ArcGIS. See example (portal item def and new web map json from ago-assistant)

![json](https://cloud.githubusercontent.com/assets/5611508/6876521/77cdb5ba-d485-11e4-8585-dac85bc428c2.jpg)

**Comment by MikeMillerGIS** [comment]
So we need to get the layer ID from the map layer and set it in the layerId section of the editing tag.  I will look at it when I move the helper to ArcRest

**Comment by MikeMillerGIS** [comment]
Added code to search the applicationProperties and update the item id, this will fix the search section and the editing.

**Comment by clareprice** [comment]
@MikeMillerGIS It appears that this is still an issue with the most recent ArcREST code. I can provide the sample stage app I am using if you want.

**Comment by MikeMillerGIS** [comment]
resolved - https://github.com/Esri/ArcREST/commit/8e9440a7dbce45ea7e1d4560ca9904e524e00a8c
